name: realtime_obj_detection
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.5.2
  google_fonts: ^4.0.3
  cupertino_icons: ^1.0.2
  tflite_v2: ^1.0.0
  camera: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/detect.tflite
    - assets/labelmap.txt
    - assets/model.tflite  # Agregado el nuevo modelo
    - assets/labels.txt    # Etiquetas del modelo de billetes
    - assets/logo.png
